#!/usr/bin/env bash
# displaying holberton 10 times
 x=1
 while [ $x -le 10 ]
 do
         if [ $x -eq 9 ]
	 then
	       echo "Holberton School"
	       echo "Hi"
	 else
	       echo "Holberton School"
	 fi
	 x=$((x +  1))
	 done
	 
	 